name: Deploy to Salesforce via SF CLI

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose Salesforce Environment"
        required: true
        default: "Sandbox"
        type: choice
        options:
          - Sandbox
          - Production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --location=global

      - name: Authenticate to Salesforce (device login)
        run: |
          if [ "${{ github.event.inputs.environment }}" == "Production" ]; then
            echo "Authenticating to Production..."
            sf org login device -o https://login.salesforce.com -a prod
          else
            echo "Authenticating to Sandbox..."
            sf org login device -o https://test.salesforce.com -a sandbox
          fi

      - name: Deploy to Salesforce using sf
        run: |
          echo "Deploying from $(pwd)"
          echo "Contents:"
          ls -R .

          if [ "${{ github.event.inputs.environment }}" == "Production" ]; then
            echo "Deploying to Production..."
            sf project deploy start --source-dir force-app --target-org prod --ignore-conflicts
          else
            echo "Deploying to Sandbox..."
            sf project deploy start --source-dir force-app --target-org sandbox --ignore-conflicts
          fi
